name: DotNet Framework CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build-and-scan:

    runs-on: self-hosted

    steps:

    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4


    # 2️⃣ Restore NuGet packages
    - name: Restore NuGet packages
      run: nuget restore SampleDotNetFrameworkApp.slnx


    # 3️⃣ Build solution using MSBuild
    - name: Build .NET Framework Solution
      shell: powershell
      run: |
        & "C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\MSBuild.exe" `
        "SampleDotNetFrameworkApp.slnx" `
        /t:Rebuild `
        /p:Configuration=Release


    # 4️⃣ Install Trivy (lightweight security scanner)
    - name: Install Trivy
      shell: powershell
      run: |
        $trivyPath = "$env:RUNNER_TEMP\trivy.exe"
        Invoke-WebRequest -Uri https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_windows-64bit.zip -OutFile trivy.zip
        Expand-Archive trivy.zip -DestinationPath $env:RUNNER_TEMP -Force
        Remove-Item trivy.zip


    # 5️⃣ Run Trivy scan
    - name: Run Trivy Security Scan
      shell: powershell
      run: |
        $trivy = Get-ChildItem $env:RUNNER_TEMP -Recurse -Filter trivy.exe | Select-Object -First 1
        & $trivy.FullName fs .
